name: Triton
recipe: lamp
config:
  public_html:
    volumes:
      - type: bind
        source: ./web
        target: /app
        cached: true
  webroot: public_html
  xdebug: false
  config:
    php: php_config/php.ini
  php: "8.1"
services:
  mailhog:
    type: "mailhog:v1.0.0"
    portforward: true
    hogfrom:
      - appserver
    appserver:
      build_as_root:
        - apt-get update -y
        - apt-get install -y php8.1-opcache
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    build:
      - composer install
proxy:
  mailhog:
    - mail.triton.lndo.site
  phpmyadmin:
    - phpmyadmin.triton.lndo.site
  appserver:
    - triton.lndo.site:8080
tooling:
  drush:
    service: appserver
excludes:
  - vendor
  - node_modules
  - modules/contrib
